---

#- name: Detect if this is a systemd based system
#  command: cat /proc/1/comm
#  register: init
#  changed_when: False
#- set_fact: use_systemd=True
#  when: init.stdout == 'systemd'
#- set_fact: use_systemd=False
#  when: init.stdout != 'systemd'

- name: Copy Kafka systemd service file
  template:
    src: kafka.systemd.service.j2
    dest: /etc/systemd/system/kafka.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
  when: ansible_service_mgr == 'upstart'

- name: Copy Kafka server-start
  template:
    src: kafka-server-start.sh.j2
    dest:  /opt/kafka/bin/kafka-server-start.sh
    owner: root
    group: root
    mode: 0755
  notify:
    - restart kafka

- name: Copy Kafka log4.properties
  template:
    src: log4j.properties.j2
    dest: /opt/kafka/config/log4j.properties
    owner: kafka
    group: kafka
    mode: 0644
  notify:
    - restart kafka

- name: Copy Kafka server.properties
  template:
    src: server.properties.j2
    dest: /opt/kafka/config/server.properties
    owner: kafka
    group: kafka
    mode: 0644
  notify:
    - restart kafka

- meta: flush_handlers
