---
- name: Copy Kafka systemd service file
  template:
    src: kafka.systemd.service.j2
    dest: /etc/systemd/system/kafka.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart kafka
  when: ansible_service_mgr == 'systemd'

- name: Copy Kafka upstart init script
  template:
    src: kafka.upstart.conf.j2
    dest: /etc/init/kafka.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - Reload upstart
    - Restart kafka
  when: ansible_service_mgr == 'upstart'

- name: Copy Kafka server-start
  template:
    src: kafka.j2
    dest:  /etc/default/kafka
    owner: root
    group: root
    mode: 0755
  notify:
    - Restart kafka

- name: Copy Kafka log4.properties
  template:
    src: log4j.properties.j2
    dest: /opt/kafka/config/log4j.properties
    owner: kafka
    group: kafka
    mode: 0644
  notify:
    - Restart kafka

- name: Copy Kafka server.properties
  template:
    src: server.properties.j2
    dest: /opt/kafka/config/server.properties
    owner: kafka
    group: kafka
    mode: 0644
  notify:
    - Restart kafka

- meta: flush_handlers
